# Generated by Django 5.2.4 on 2025-07-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('bright_ti4', models.FloatField()),
                ('acq_date', models.DateField()),
                ('acq_time', models.CharField(max_length=10)),
                ('confidence', models.CharField(max_length=10)),
                ('frp', models.FloatField()),
                ('daynight', models.CharField(max_length=1)),
            ],
        ),
    ]
